Repository dnd-side-project/dnd-9th-2-backend, pull requests merged in 2023-09, with the labels that each got.

#137 [refactor] 모임 생성 & 전체 모임 조회 비즈니스 로직 리팩터링
  src/main/java/org/baggle/domain/meeting/repository/MeetingRepository.java
  src/main/java/org/baggle/domain/meeting/service/MeetingService.java
  src/main/java/org/baggle/global/common/TimeConverter.java
Labels: feat, fix, refactor, 선웅 🍃

#138 [feat] 모임 탈퇴 api 구현
  src/main/java/org/baggle/domain/meeting/controller/ParticipationApiController.java
  src/main/java/org/baggle/domain/meeting/service/ParticipationService.java
Labels: feat, 관곤 🍃

#140 [refactor] timeConvert 적용
  src/main/java/org/baggle/domain/meeting/service/MeetingDetailService.java
  src/main/java/org/baggle/domain/meeting/service/ParticipationService.java
  src/main/java/org/baggle/global/common/TimeConverter.java
Labels: refactor, 관곤 🍃

#142 [fix] 소셜 로그인 비즈니스 로직 수정
  src/main/java/org/baggle/domain/user/service/AuthService.java
Labels: fix, 선웅 🍃

#144 [feat] 모임 생성 비즈니스 로직 예외 추가
  src/main/java/org/baggle/domain/meeting/service/MeetingService.java
Labels: feat, 선웅 🍃

#146 [fix] 전체 모임 조회 남은 기간 오류 수정
  src/main/java/org/baggle/domain/meeting/dto/response/MeetingResponseDto.java
  src/main/java/org/baggle/global/common/TimeConverter.java
Labels: feat, fix, 선웅 🍃

#148 [fix] scheduler 시간 오류 수정
  src/main/java/org/baggle/domain/fcm/scheduler/NotificationScheduler.java
  src/main/java/org/baggle/domain/meeting/scheduler/MeetingScheduler.java
  src/main/java/org/baggle/domain/meeting/service/MeetingDetailService.java
Labels: fix, 관곤 🍃

#151 [fix] 모임 수정 api 로직 수정
  src/main/java/org/baggle/domain/meeting/controller/ParticipationApiController.java
  src/main/java/org/baggle/domain/meeting/service/MeetingDetailService.java
Labels: fix, del, 관곤 🍃

#153 [fix] 모임 폭파 api 시간 예외처리 수정
  src/main/java/org/baggle/domain/meeting/service/MeetingDetailService.java
Labels: fix, 관곤 🍃

#155 [fix] 전체 모임 조회 정렬 오류 수정
  src/main/java/org/baggle/domain/meeting/repository/MeetingRepository.java
  src/main/java/org/baggle/domain/meeting/service/MeetingService.java
Labels: fix, 선웅 🍃

#157 [fix] 모임 확정 알림시 빈 fcm token 오류 해결
  src/main/java/org/baggle/domain/fcm/domain/FcmNotification.java
  src/main/java/org/baggle/domain/fcm/scheduler/NotificationScheduler.java
  src/main/java/org/baggle/domain/fcm/service/FcmNotificationService.java
  src/main/java/org/baggle/domain/meeting/service/MeetingDetailService.java
  src/main/java/org/baggle/infra/redis/ExpirationListener.java
Labels: fix, del, 관곤 🍃

#158 [feat] JWT 재발급 401 예외 시 로그아웃 기능 추가
  src/main/java/org/baggle/domain/user/controller/AuthApiController.java
  src/main/java/org/baggle/domain/user/dto/request/UserReissueRequestDto.java
  src/main/java/org/baggle/domain/user/service/AuthService.java
  src/main/java/org/baggle/global/config/jwt/JwtProvider.java
Labels: feat, fix, refactor, 선웅 🍃

#160 [fix] 모임 상태 변경 로직 수정 Termination -> past
  src/main/java/org/baggle/domain/meeting/scheduler/MeetingScheduler.java
Labels: fix, 관곤 🍃

#162 [fix] 긴급소집 fcm 알람 오류 해결
  src/main/java/org/baggle/domain/feed/service/FeedService.java
Labels: fix, 관곤 🍃

#166 [fix] 모임 생성 예외 처리 변경사항 적용
  src/main/java/org/baggle/BaggleApplication.java
  src/main/java/org/baggle/domain/meeting/controller/MeetingApiController.java
  src/main/java/org/baggle/domain/meeting/domain/Meeting.java
  src/main/java/org/baggle/domain/meeting/dto/response/GetMeetingsResponseDto.java
  src/main/java/org/baggle/domain/meeting/repository/MeetingRepository.java
  src/main/java/org/baggle/domain/meeting/service/MeetingService.java
  src/main/java/org/baggle/global/error/exception/ErrorCode.java
Labels: feat, fix, del, refactor, chore, 선웅 🍃

#168 [fix] feed fcmToken 오류 로직 해결
  src/main/java/org/baggle/domain/feed/service/FeedService.java
Labels: fix, 관곤 🍃

#171 [feat] 신고 api 구현
  src/main/java/org/baggle/domain/feed/domain/Feed.java
  src/main/java/org/baggle/domain/feed/service/FeedService.java
  src/main/java/org/baggle/domain/meeting/domain/Participation.java
  src/main/java/org/baggle/domain/meeting/domain/Report.java
  src/main/java/org/baggle/domain/report/controller/ReportApiController.java
  src/main/java/org/baggle/domain/report/domain/Report.java
  src/main/java/org/baggle/domain/report/domain/ReportType.java
  src/main/java/org/baggle/domain/report/dto/request/CreateReportRequestDto.java
  src/main/java/org/baggle/domain/report/repository/ReportRepository.java
  src/main/java/org/baggle/domain/report/service/ReportService.java
  src/main/java/org/baggle/global/error/exception/ErrorCode.java
  src/main/resources/db/migration/V5__add_report_type.sql
Labels: feat, refactor, 관곤 🍃

#173 [feat] 운영 서버 & 테스트 서버 분리
  .github/workflows/ cicd.yml
  .github/workflows/cd-dev.yml
  .github/workflows/cd-prod.yml
  .github/workflows/ci-dev.yml
  .github/workflows/ci-prod.yml
Labels: del, chore, 선웅 🍃

#175 [chore] CI/CD workflow 오류 수정
  .github/workflows/ci-dev.yml
  .github/workflows/ci-prod.yml
  .github/workflows/cicd-dev.yml
  .github/workflows/cicd-prod.yml
Labels: chore, 선웅 🍃

#177 [chore] CI/CD workflow 오타 수정
  .github/workflows/ci-dev.yml
  .github/workflows/ci-prod.yml
  .github/workflows/cicd-dev.yml
  .github/workflows/cicd-prod.yml
Labels: chore, 선웅 🍃

#178 [feat] 모임 인원 1명에 대한 예외 처리 구현
  src/main/java/org/baggle/domain/fcm/scheduler/NotificationScheduler.java
  src/main/java/org/baggle/domain/fcm/service/FcmNotificationProvider.java
  src/main/java/org/baggle/domain/meeting/service/MeetingDetailService.java
  src/main/resources/messages_ko_KR.properties
Labels: feat, 관곤 🍃

#180 [fix] 모임상세 api에 신고 내용 추가
  src/main/java/org/baggle/domain/meeting/dto/response/MeetingDetailResponseDto.java
  src/main/java/org/baggle/domain/meeting/dto/response/ParticipationDetailResponseDto.java
  src/main/java/org/baggle/domain/meeting/service/MeetingDetailService.java
  src/main/java/org/baggle/domain/meeting/service/ParticipationService.java
  src/main/java/org/baggle/domain/report/repository/ReportRepository.java
  src/main/java/org/baggle/domain/report/service/ReportService.java
  src/main/java/org/baggle/global/error/exception/ErrorCode.java
Labels: feat, fix, refactor, 관곤 🍃

#182 [fix] report api 신고자 변수명 수정
  src/main/java/org/baggle/domain/report/dto/request/CreateReportRequestDto.java
  src/main/java/org/baggle/domain/report/service/ReportService.java
Labels: fix, 관곤 🍃

#184 [feat] report table unique 제약 조건 취소
  src/main/resources/db/migration/V6__modify_report_particicpation.sql
Labels: feat, 관곤 🍃

#187 [refactor] 코드 정리 & 테스트 yml 변경
  src/main/java/org/baggle/domain/fcm/domain/FcmNotification.java
  src/main/java/org/baggle/domain/fcm/domain/FcmTimer.java
  src/main/java/org/baggle/domain/fcm/dto/response/AddFcmTokenResponseDto.java
  src/main/java/org/baggle/domain/fcm/dto/response/GetFcmTokenResponseDto.java
  src/main/java/org/baggle/domain/fcm/dto/response/UpdateFcmTokenResponseDto.java
  src/main/java/org/baggle/domain/feed/domain/Feed.java
  src/main/java/org/baggle/domain/meeting/domain/Meeting.java
  src/main/java/org/baggle/domain/meeting/domain/Participation.java
  src/main/java/org/baggle/domain/meeting/domain/Period.java
  src/main/java/org/baggle/domain/report/domain/Report.java
  src/main/java/org/baggle/domain/report/domain/ReportType.java
  src/main/java/org/baggle/domain/user/domain/Platform.java
  src/main/java/org/baggle/domain/user/domain/RefreshToken.java
  src/main/java/org/baggle/domain/user/domain/User.java
  src/main/java/org/baggle/global/common/BaseResponse.java
  src/main/java/org/baggle/global/error/dto/ErrorBaseResponse.java
  src/main/java/org/baggle/infra/redis/ExpirationListener.java
  src/main/java/org/baggle/infra/redis/RedisDataType.java
  src/main/java/org/baggle/infra/s3/S3Config.java
  src/main/java/org/baggle/infra/s3/S3Provider.java
Labels: refactor, 선웅 🍃
