Repository dnd-side-project/dnd-9th-2-backend, pull requests merged in 2023-08, with the labels that each got.

#9 [feat] Spring Security & JWT 설정 세팅
  build.gradle
  src/main/java/org/baggle/BaggleApplication.java
  src/main/java/org/baggle/domain/sample/controller/SampleApiController.java
  src/main/java/org/baggle/domain/sample/domain/Sample.java
  src/main/java/org/baggle/domain/sample/dto/request/SampleRequestDto.java
  src/main/java/org/baggle/domain/sample/dto/response/SampleResponseDto.java
  src/main/java/org/baggle/domain/sample/repository/SampleRepository.java
  src/main/java/org/baggle/domain/sample/service/SampleService.java
  src/main/java/org/baggle/global/common/BaseTimeEntity.java
  src/main/java/org/baggle/global/config/JpaConfig.java
  src/main/java/org/baggle/global/config/auth/ExceptionHandlerFilter.java
  src/main/java/org/baggle/global/config/auth/JwtAuthenticationEntryPoint.java
  src/main/java/org/baggle/global/config/auth/JwtAuthenticationFilter.java
  src/main/java/org/baggle/global/config/auth/SecurityConfig.java
  src/main/java/org/baggle/global/config/auth/UserAuthentication.java
  src/main/java/org/baggle/global/config/jwt/JwtProvider.java
  src/main/java/org/baggle/global/config/jwt/Token.java
  src/main/java/org/baggle/global/error/exception/ErrorCode.java
  src/main/java/org/baggle/infra/s3/S3Config.java
  src/main/java/org/baggle/infra/s3/S3Service.java
Labels: feat, chore, 선웅 🍃

#12 [feat] @Entity 클래스 구현
  src/main/java/org/baggle/domain/feed/domain/Feed.java
  src/main/java/org/baggle/domain/meeting/domain/ButtonAuthority.java
  src/main/java/org/baggle/domain/meeting/domain/ButtonStatus.java
  src/main/java/org/baggle/domain/meeting/domain/Meeting.java
  src/main/java/org/baggle/domain/meeting/domain/MeetingAuthority.java
  src/main/java/org/baggle/domain/meeting/domain/MeetingStatus.java
  src/main/java/org/baggle/domain/meeting/domain/Participation.java
  src/main/java/org/baggle/domain/meeting/domain/ParticipationMeetingStatus.java
  src/main/java/org/baggle/domain/meeting/domain/Report.java
  src/main/java/org/baggle/domain/user/domain/User.java
  src/main/java/org/baggle/global/common/BaseTimeEntity.java
Labels: feat, fix, 선웅 🍃

#14 [feat] FCM 알림 설정 & 구현
  .github/workflows/ cicd.yml
  .gitignore
  build.gradle
  src/main/java/org/baggle/domain/fcm/controller/FCMController.java
  src/main/java/org/baggle/domain/fcm/domain/FCMToken.java
  src/main/java/org/baggle/domain/fcm/dto/request/AddFCMTokenRequestDto.java
  src/main/java/org/baggle/domain/fcm/dto/request/FCMNotificationRequestDto.java
  src/main/java/org/baggle/domain/fcm/dto/request/UpdateFCMTokenRequestDto.java
  src/main/java/org/baggle/domain/fcm/dto/response/AddFCMTokenResponseDto.java
  src/main/java/org/baggle/domain/fcm/dto/response/GetFCMTokenResponseDto.java
  src/main/java/org/baggle/domain/fcm/dto/response/UpdateFCMTokenResponseDto.java
  src/main/java/org/baggle/domain/fcm/repository/FCMRepository.java
  src/main/java/org/baggle/domain/fcm/service/FCMNotificationService.java
  src/main/java/org/baggle/domain/fcm/service/FCMService.java
  src/main/java/org/baggle/domain/user/domain/User.java
  src/main/java/org/baggle/global/error/exception/ErrorCode.java
  src/main/java/org/baggle/infra/fcm/FCMConfig.java
  src/main/resources/db/migration/V2__add_init_table.sql
Labels: feat, chore, 관곤 🍃

#15 [feat] JWT & Redis 세팅
  src/main/java/org/baggle/domain/user/controller/AuthApiController.java
  src/main/java/org/baggle/domain/user/domain/RefreshToken.java
  src/main/java/org/baggle/domain/user/dto/request/UserSignInRequestDto.java
  src/main/java/org/baggle/domain/user/dto/response/UserAuthResponseDto.java
  src/main/java/org/baggle/domain/user/repository/RefreshTokenRepository.java
  src/main/java/org/baggle/domain/user/repository/UserRepository.java
  src/main/java/org/baggle/domain/user/service/AuthService.java
  src/main/java/org/baggle/global/config/jwt/JwtProvider.java
Labels: feat, refactor, 선웅 🍃

#19 [fix] Database 테이블 & @Entity 클래스 수정
  src/main/java/org/baggle/domain/fcm/domain/FCMToken.java
  src/main/java/org/baggle/domain/fcm/service/FCMService.java
  src/main/java/org/baggle/domain/meeting/domain/ButtonStatus.java
  src/main/java/org/baggle/domain/meeting/domain/Meeting.java
  src/main/java/org/baggle/domain/sample/controller/SampleApiController.java
  src/main/java/org/baggle/domain/sample/domain/Sample.java
  src/main/java/org/baggle/domain/sample/dto/request/SampleRequestDto.java
  src/main/java/org/baggle/domain/sample/dto/response/SampleResponseDto.java
  src/main/java/org/baggle/domain/sample/exception/SampleDuplicateException.java
  src/main/java/org/baggle/domain/sample/repository/SampleRepository.java
  src/main/java/org/baggle/domain/sample/service/SampleService.java
  src/main/resources/db/migration/V2__add_init_table.sql
Labels: fix, del, 선웅 🍃

#20 [feat] 애플 소셜 로그인 기능 구현
  build.gradle
  src/main/java/org/baggle/domain/user/auth/apple/AppleFeignClient.java
  src/main/java/org/baggle/domain/user/auth/apple/AppleOAuthProvider.java
  src/main/java/org/baggle/domain/user/auth/apple/ApplePublicKey.java
  src/main/java/org/baggle/domain/user/auth/apple/ApplePublicKeys.java
  src/main/java/org/baggle/domain/user/auth/apple/IdentityTokenParser.java
  src/main/java/org/baggle/domain/user/auth/apple/IdentityTokenValidator.java
  src/main/java/org/baggle/domain/user/auth/apple/PublicKeyGenerator.java
  src/main/java/org/baggle/domain/user/dto/request/UserSignInRequestDto.java
  src/main/java/org/baggle/domain/user/dto/response/UserAuthResponseDto.java
  src/main/java/org/baggle/domain/user/service/AuthService.java
  src/main/java/org/baggle/global/config/FeignClientConfig.java
  src/main/java/org/baggle/global/error/exception/ErrorCode.java
Labels: feat, chore, 선웅 🍃

#22 [feat] 알람 전송 Scheduler 구현 & 링크 참여, 모임 상세 api 구현
  src/main/java/org/baggle/BaggleApplication.java
  src/main/java/org/baggle/domain/fcm/controller/FCMController.java
  src/main/java/org/baggle/domain/fcm/domain/FcmNotification.java
  src/main/java/org/baggle/domain/fcm/domain/FcmTimer.java
  src/main/java/org/baggle/domain/fcm/domain/FcmToken.java
  src/main/java/org/baggle/domain/fcm/dto/request/AddFCMTokenRequestDto.java
  src/main/java/org/baggle/domain/fcm/dto/request/AddFcmTokenRequestDto.java
  src/main/java/org/baggle/domain/fcm/dto/request/FCMNotificationRequestDto.java
  src/main/java/org/baggle/domain/fcm/dto/request/FcmNotificationRequestDto.java
  src/main/java/org/baggle/domain/fcm/dto/request/UpdateFcmTokenRequestDto.java
  src/main/java/org/baggle/domain/fcm/dto/response/AddFCMTokenResponseDto.java
  src/main/java/org/baggle/domain/fcm/dto/response/AddFcmTokenResponseDto.java
  src/main/java/org/baggle/domain/fcm/dto/response/GetFCMTokenResponseDto.java
  src/main/java/org/baggle/domain/fcm/dto/response/GetFcmTokenResponseDto.java
  src/main/java/org/baggle/domain/fcm/dto/response/UpdateFCMTokenResponseDto.java
  src/main/java/org/baggle/domain/fcm/dto/response/UpdateFcmTokenResponseDto.java
  src/main/java/org/baggle/domain/fcm/repository/FCMRepository.java
  src/main/java/org/baggle/domain/fcm/repository/FcmNotificationRepository.java
  src/main/java/org/baggle/domain/fcm/repository/FcmRepository.java
  src/main/java/org/baggle/domain/fcm/repository/FcmTimerRepository.java
  src/main/java/org/baggle/domain/fcm/scheduler/NotificationScheduler.java
  src/main/java/org/baggle/domain/fcm/service/FCMNotificationService.java
  src/main/java/org/baggle/domain/fcm/service/FCMService.java
  src/main/java/org/baggle/domain/fcm/service/FcmNotificationService.java
  src/main/java/org/baggle/domain/fcm/service/FcmService.java
  src/main/java/org/baggle/domain/feed/repository/FeedRepository.java
  src/main/java/org/baggle/domain/meeting/controller/MeetingController.java
  src/main/java/org/baggle/domain/meeting/controller/ParticipationController.java
  src/main/java/org/baggle/domain/meeting/domain/ButtonAuthority.java
  src/main/java/org/baggle/domain/meeting/domain/MeetingAuthority.java
  src/main/java/org/baggle/domain/meeting/domain/MeetingStatus.java
  src/main/java/org/baggle/domain/meeting/domain/Participation.java
  src/main/java/org/baggle/domain/meeting/domain/ParticipationMeetingStatus.java
  src/main/java/org/baggle/domain/meeting/dto/reponse/MeetingDetailResponseDto.java
  src/main/java/org/baggle/domain/meeting/dto/reponse/ParticipationAvailabilityResponseDto.java
  src/main/java/org/baggle/domain/meeting/dto/reponse/ParticipationDetailResponseDto.java
  src/main/java/org/baggle/domain/meeting/dto/reponse/ParticipationResponseDto.java
  src/main/java/org/baggle/domain/meeting/dto/request/ParticipationReqeustDto.java
  src/main/java/org/baggle/domain/meeting/repository/MeetingRepository.java
  src/main/java/org/baggle/domain/meeting/repository/ParticipationRepository.java
  src/main/java/org/baggle/domain/meeting/service/MeetingService.java
  src/main/java/org/baggle/domain/meeting/service/ParticipationService.java
  src/main/java/org/baggle/domain/user/domain/Platform.java
  src/main/java/org/baggle/domain/user/domain/User.java
  src/main/java/org/baggle/global/error/exception/ErrorCode.java
  src/main/java/org/baggle/infra/fcm/FcmConfig.java
  src/main/java/org/baggle/infra/redis/ExpirationListener.java
  src/main/java/org/baggle/infra/redis/RedisConfig.java
  src/main/resources/db/migration/V1__add_init_table.sql
  src/main/resources/db/migration/V1__init_test.sql
  src/main/resources/db/migration/V2__modify_check_constraint.sql
Labels: feat, fix, refactor, chore, 관곤 🍃

#24 [feat] 애플 회원 가입 API 구현
  src/main/java/org/baggle/domain/fcm/domain/FcmToken.java
  src/main/java/org/baggle/domain/meeting/repository/MeetingRepository.java
  src/main/java/org/baggle/domain/user/auth/apple/PublicKeyGenerator.java
  src/main/java/org/baggle/domain/user/controller/AuthApiController.java
  src/main/java/org/baggle/domain/user/domain/Platform.java
  src/main/java/org/baggle/domain/user/domain/RefreshToken.java
  src/main/java/org/baggle/domain/user/domain/User.java
  src/main/java/org/baggle/domain/user/dto/response/UserAuthResponseDto.java
  src/main/java/org/baggle/domain/user/repository/UserRepository.java
  src/main/java/org/baggle/domain/user/service/AuthService.java
  src/main/java/org/baggle/global/common/ImageType.java
  src/main/java/org/baggle/global/config/auth/SecurityConfig.java
  src/main/java/org/baggle/global/error/exception/ErrorCode.java
  src/main/java/org/baggle/infra/s3/S3Service.java
Labels: feat, fix, refactor, chore, 선웅 🍃

#25 [feat] 인증 사진 업로드 & 긴급소집 알람 전송 api 구현
  src/main/java/org/baggle/domain/fcm/service/FcmNotificationService.java
  src/main/java/org/baggle/domain/feed/controller/FeedController.java
  src/main/java/org/baggle/domain/feed/domain/Feed.java
  src/main/java/org/baggle/domain/feed/dto/request/FeedUploadRequestDto.java
  src/main/java/org/baggle/domain/feed/dto/response/FeedNotificationResponseDto.java
  src/main/java/org/baggle/domain/feed/dto/response/FeedUploadResponseDto.java
  src/main/java/org/baggle/domain/feed/service/FeedService.java
  src/main/java/org/baggle/global/error/exception/ErrorCode.java
  src/main/java/org/baggle/infra/redis/ExpirationListener.java
Labels: feat, refactor, 관곤 🍃

#27 [refactor] 링크참여 api 오류 처리 개선
  src/main/java/org/baggle/domain/fcm/scheduler/NotificationScheduler.java
  src/main/java/org/baggle/domain/meeting/service/MeetingService.java
  src/main/java/org/baggle/domain/meeting/service/ParticipationService.java
  src/main/java/org/baggle/global/error/exception/ErrorCode.java
Labels: feat, refactor, 관곤 🍃

#30 [refactor] 인증 사진 업로드 & 긴급소집 알람 api 예외 처리 개선
  src/main/java/org/baggle/domain/fcm/service/FcmNotificationService.java
  src/main/java/org/baggle/domain/fcm/service/FcmService.java
  src/main/java/org/baggle/domain/feed/dto/request/FeedUploadRequestDto.java
  src/main/java/org/baggle/domain/feed/service/FeedService.java
  src/main/java/org/baggle/domain/meeting/service/MeetingService.java
  src/main/java/org/baggle/domain/meeting/service/ParticipationService.java
  src/main/java/org/baggle/global/error/exception/ErrorCode.java
  src/main/java/org/baggle/infra/redis/ExpirationListener.java
Labels: feat, fix, refactor, 관곤 🍃

#31 [feat] 애플 회원 가입 API 변경 사항 추가
  src/main/java/org/baggle/domain/user/controller/AuthApiController.java
  src/main/java/org/baggle/domain/user/dto/response/UserAuthResponseDto.java
  src/main/java/org/baggle/domain/user/repository/UserRepository.java
  src/main/java/org/baggle/domain/user/service/AuthService.java
  src/main/java/org/baggle/global/error/exception/ErrorCode.java
Labels: feat, fix, 선웅 🍃

#33 [refactor] 애플 회원 가입 API 오류 코드 추가
  src/main/java/org/baggle/domain/user/auth/apple/AppleOAuthProvider.java
  src/main/java/org/baggle/domain/user/auth/apple/IdentityTokenParser.java
  src/main/java/org/baggle/global/error/exception/ErrorCode.java
Labels: feat, refactor, 선웅 🍃

#35 [feat] 애플 회원 가입 API 오류 로그 확인 코드 추가
  src/main/java/org/baggle/domain/user/auth/apple/IdentityTokenParser.java
Labels: feat, 선웅 🍃

#37 [fix] 애플 회원 가입 API identity token 파싱 메서드 변경
  src/main/java/org/baggle/domain/user/auth/apple/IdentityTokenParser.java
Labels: fix, 선웅 🍃

#40 [fix] 애플 회원 가입 API 오류 수정
  src/main/java/org/baggle/domain/user/domain/RefreshToken.java
  src/main/java/org/baggle/domain/user/domain/User.java
  src/main/java/org/baggle/domain/user/dto/response/UserAuthResponseDto.java
  src/main/java/org/baggle/domain/user/service/AuthService.java
  src/main/java/org/baggle/global/config/jwt/JwtProvider.java
Labels: feat, fix, 선웅 🍃

#41 [feat] 1순위 api controller 구현
  src/main/java/org/baggle/domain/fcm/scheduler/NotificationScheduler.java
  src/main/java/org/baggle/domain/fcm/service/FcmNotificationService.java
  src/main/java/org/baggle/domain/feed/controller/FeedController.java
  src/main/java/org/baggle/domain/feed/dto/request/FeedUploadRequestDto.java
  src/main/java/org/baggle/domain/feed/service/FeedService.java
  src/main/java/org/baggle/domain/meeting/controller/MeetingController.java
  src/main/java/org/baggle/domain/meeting/controller/ParticipationController.java
  src/main/java/org/baggle/domain/meeting/domain/Participation.java
  src/main/java/org/baggle/domain/meeting/dto/request/ParticipationReqeustDto.java
  src/main/java/org/baggle/domain/meeting/service/MeetingService.java
  src/main/java/org/baggle/domain/meeting/service/ParticipationService.java
  src/main/java/org/baggle/global/error/exception/ErrorCode.java
Labels: feat, fix, refactor, chore, 관곤 🍃

#43 [feat] 회원 탈퇴 API 구현
  src/main/java/org/baggle/domain/fcm/domain/FcmToken.java
  src/main/java/org/baggle/domain/user/auth/apple/IdentityTokenParser.java
  src/main/java/org/baggle/domain/user/controller/AuthApiController.java
  src/main/java/org/baggle/domain/user/domain/User.java
  src/main/java/org/baggle/domain/user/service/AuthService.java
  src/main/java/org/baggle/global/config/WebConfig.java
  src/main/java/org/baggle/global/config/auth/ExceptionHandlerFilter.java
  src/main/java/org/baggle/global/config/auth/JwtAuthenticationFilter.java
  src/main/java/org/baggle/global/config/auth/SecurityConfig.java
  src/main/java/org/baggle/global/config/auth/UserId.java
  src/main/java/org/baggle/global/config/auth/UserIdArgumentResolver.java
  src/main/java/org/baggle/global/config/jwt/JwtProvider.java
  src/main/java/org/baggle/global/error/exception/ErrorCode.java
  src/main/resources/db/migration/V3__modify_table.sql
Labels: feat, fix, del, refactor, chore, 선웅 🍃

#46 [feat] 애플 로그인 API 구현
  src/main/java/org/baggle/domain/fcm/domain/FcmToken.java
  src/main/java/org/baggle/domain/fcm/repository/FcmRepository.java
  src/main/java/org/baggle/domain/user/domain/User.java
  src/main/java/org/baggle/domain/user/dto/request/UserSignInRequestDto.java
  src/main/java/org/baggle/domain/user/repository/UserRepository.java
  src/main/java/org/baggle/domain/user/service/AuthService.java
  src/main/java/org/baggle/global/config/auth/SecurityConfig.java
Labels: feat, fix, refactor, chore, 선웅 🍃

#48 [fix] 회원 탈퇴 API 반환 값 변경
  src/main/java/org/baggle/domain/user/controller/AuthApiController.java
  src/main/java/org/baggle/domain/user/service/AuthService.java
Labels: fix, 선웅 🍃

#49 [fix] 링크 참여 api 예외처리 개선
  src/main/java/org/baggle/domain/meeting/controller/ParticipationController.java
  src/main/java/org/baggle/domain/meeting/service/ParticipationService.java
  src/main/java/org/baggle/global/error/exception/ErrorCode.java
Labels: feat, fix, 관곤 🍃

#51 [feat] 모임 수정 api 구현 & 1순위 api 배포
  src/main/java/org/baggle/domain/fcm/domain/FcmTimer.java
  src/main/java/org/baggle/domain/fcm/dto/request/AddFcmTokenRequestDto.java
  src/main/java/org/baggle/domain/fcm/dto/request/FcmNotificationRequestDto.java
  src/main/java/org/baggle/domain/fcm/dto/request/UpdateFcmTokenRequestDto.java
  src/main/java/org/baggle/domain/feed/controller/FeedApiController.java
  src/main/java/org/baggle/domain/feed/controller/FeedController.java
  src/main/java/org/baggle/domain/feed/service/FeedService.java
  src/main/java/org/baggle/domain/meeting/controller/MeetingApiController.java
  src/main/java/org/baggle/domain/meeting/controller/MeetingController.java
  src/main/java/org/baggle/domain/meeting/controller/ParticipationApiController.java
  src/main/java/org/baggle/domain/meeting/controller/ParticipationController.java
  src/main/java/org/baggle/domain/meeting/domain/Meeting.java
  src/main/java/org/baggle/domain/meeting/dto/request/ParticipationReqeustDto.java
  src/main/java/org/baggle/domain/meeting/dto/request/UpdateMeetingInfoRequestDto.java
  src/main/java/org/baggle/domain/meeting/dto/response/MeetingDetailResponseDto.java
  src/main/java/org/baggle/domain/meeting/dto/response/ParticipationAvailabilityResponseDto.java
  src/main/java/org/baggle/domain/meeting/dto/response/ParticipationDetailResponseDto.java
  src/main/java/org/baggle/domain/meeting/dto/response/ParticipationResponseDto.java
  src/main/java/org/baggle/domain/meeting/dto/response/UpdateMeetingInfoResponseDto.java
  src/main/java/org/baggle/domain/meeting/repository/MeetingRepository.java
  src/main/java/org/baggle/domain/meeting/repository/ParticipationRepository.java
  src/main/java/org/baggle/domain/meeting/service/MeetingService.java
  src/main/java/org/baggle/domain/meeting/service/ParticipationService.java
  src/main/java/org/baggle/global/error/exception/ErrorCode.java
Labels: feat, fix, 관곤 🍃

#54 [feat] Meeting Status 변환 로직 구현
  src/main/java/org/baggle/domain/fcm/scheduler/NotificationScheduler.java
  src/main/java/org/baggle/domain/feed/service/FeedService.java
  src/main/java/org/baggle/domain/meeting/controller/ParticipationApiController.java
  src/main/java/org/baggle/domain/meeting/domain/Meeting.java
  src/main/java/org/baggle/domain/meeting/service/ParticipationService.java
  src/main/java/org/baggle/global/error/exception/ErrorCode.java
  src/main/java/org/baggle/infra/redis/ExpirationListener.java
Labels: feat, fix, refactor, 관곤 🍃

#56 [feat] 카카오 OAuth Provider 구현
  src/main/java/org/baggle/domain/user/auth/kakao/KakaoAccessToken.java
  src/main/java/org/baggle/domain/user/auth/kakao/KakaoAccessTokenFeignClient.java
  src/main/java/org/baggle/domain/user/auth/kakao/KakaoAccessTokenInfo.java
  src/main/java/org/baggle/domain/user/auth/kakao/KakaoAccessTokenInfoFeignClient.java
  src/main/java/org/baggle/domain/user/auth/kakao/KakaoAccessTokenRequestDto.java
  src/main/java/org/baggle/domain/user/auth/kakao/KakaoOAuthProvider.java
  src/main/java/org/baggle/global/error/exception/ErrorCode.java
Labels: feat, 선웅 🍃

#58 [feat] 카카오 로그인 & 회원 가입 비즈니스 로직 구현
  src/main/java/org/baggle/domain/feed/service/FeedService.java
  src/main/java/org/baggle/domain/user/service/AuthService.java
  src/main/java/org/baggle/global/config/auth/JwtAuthenticationFilter.java
  src/main/java/org/baggle/infra/s3/S3Provider.java
Labels: feat, refactor, 선웅 🍃

#60 [fix] 카카오 OAuth Provider 오류 수정
  src/main/java/org/baggle/domain/user/auth/kakao/KakaoAccessTokenFeignClient.java
  src/main/java/org/baggle/domain/user/auth/kakao/KakaoAccessTokenRequestDto.java
  src/main/java/org/baggle/domain/user/auth/kakao/KakaoOAuthProvider.java
  src/main/java/org/baggle/global/error/exception/ErrorCode.java
Labels: fix, del, 선웅 🍃

#61 [refactor] ExpireListener & FeedService 코드 refactor
  src/main/java/org/baggle/global/error/exception/ErrorCode.java
  src/main/java/org/baggle/infra/redis/ExpirationListener.java
  src/main/java/org/baggle/infra/redis/RedisDataType.java
Labels: feat, fix, refactor, 관곤 🍃

#63 [feat] 카카오 OAuth Feign Client 오류 로그 코드 추가
  src/main/java/org/baggle/domain/user/auth/kakao/KakaoOAuthProvider.java
Labels: feat, 선웅 🍃

#65 [fix] 링크 참여 로직 수정
  src/main/java/org/baggle/domain/fcm/scheduler/NotificationScheduler.java
  src/main/java/org/baggle/domain/meeting/service/MeetingService.java
  src/main/java/org/baggle/domain/meeting/service/ParticipationService.java
  src/main/java/org/baggle/global/error/exception/ErrorCode.java
  src/main/java/org/baggle/infra/redis/ExpirationListener.java
Labels: fix, refactor, 관곤 🍃

#67 [fix] 카카오 OAuth Provider 로직 수정
  src/main/java/org/baggle/domain/user/auth/kakao/KakaoAccessToken.java
  src/main/java/org/baggle/domain/user/auth/kakao/KakaoAccessTokenFeignClient.java
  src/main/java/org/baggle/domain/user/auth/kakao/KakaoFeignClient.java
  src/main/java/org/baggle/domain/user/auth/kakao/KakaoOAuthProvider.java
  src/main/java/org/baggle/domain/user/service/AuthService.java
  src/main/java/org/baggle/global/error/exception/ErrorCode.java
Labels: fix, refactor, 선웅 🍃

#69 [fix] LocalDateTime Json 직렬화하기
  src/main/java/org/baggle/domain/feed/dto/response/FeedNotificationResponseDto.java
  src/main/java/org/baggle/domain/meeting/dto/response/MeetingDetailResponseDto.java
  src/main/java/org/baggle/domain/meeting/dto/response/ParticipationAvailabilityResponseDto.java
  src/main/java/org/baggle/domain/meeting/dto/response/UpdateMeetingInfoResponseDto.java
Labels: fix, 관곤 🍃

#71 [fix] Meeting Detail response dto 날짜 중복 데이터 수정
  src/main/java/org/baggle/domain/meeting/dto/response/MeetingDetailResponseDto.java
  src/main/java/org/baggle/domain/meeting/service/MeetingService.java
Labels: fix, 관곤 🍃

#79 [fix] 카메라 인증 api 수정
  docker-compose.yml
  src/main/java/org/baggle/BaggleApplication.java
  src/main/java/org/baggle/domain/feed/controller/FeedApiController.java
  src/main/java/org/baggle/domain/feed/dto/request/FeedUploadRequestDto.java
  src/main/java/org/baggle/domain/feed/dto/response/FeedUploadResponseDto.java
  src/main/java/org/baggle/domain/feed/repository/FeedRepository.java
  src/main/java/org/baggle/domain/feed/service/FeedService.java
  src/main/java/org/baggle/global/error/exception/ErrorCode.java
Labels: feat, fix, refactor, 관곤 🍃

#80 [feat] 모임 생성 API 구현
  src/main/java/org/baggle/domain/fcm/scheduler/NotificationScheduler.java
  src/main/java/org/baggle/domain/meeting/controller/MeetingApiController.java
  src/main/java/org/baggle/domain/meeting/controller/ParticipationApiController.java
  src/main/java/org/baggle/domain/meeting/domain/Meeting.java
  src/main/java/org/baggle/domain/meeting/domain/Participation.java
  src/main/java/org/baggle/domain/meeting/dto/request/CreateMeetingRequestDto.java
  src/main/java/org/baggle/domain/meeting/dto/request/ParticipationRequestDto.java
  src/main/java/org/baggle/domain/meeting/repository/MeetingRepository.java
  src/main/java/org/baggle/domain/meeting/service/MeetingDetailService.java
  src/main/java/org/baggle/domain/meeting/service/MeetingService.java
  src/main/java/org/baggle/domain/meeting/service/ParticipationService.java
  src/main/java/org/baggle/domain/user/domain/User.java
  src/main/java/org/baggle/global/error/exception/ErrorCode.java
Labels: feat, fix, chore, 선웅 🍃

#84 [fix] 링크 참여 post api response 값 수정
  src/main/java/org/baggle/domain/meeting/controller/ParticipationApiController.java
Labels: fix, 관곤 🍃

#87 [feat] 모임참여 버튼 할당자 로직 구현
  src/main/java/org/baggle/domain/meeting/domain/Meeting.java
  src/main/java/org/baggle/domain/meeting/domain/Participation.java
  src/main/java/org/baggle/domain/meeting/service/ParticipationService.java
Labels: feat, 관곤 🍃

#89 [fix] fcm 알람 전송 예외 처리 수정
  src/main/java/org/baggle/domain/fcm/scheduler/NotificationScheduler.java
  src/main/java/org/baggle/domain/fcm/service/FcmNotificationProvider.java
  src/main/java/org/baggle/domain/fcm/service/FcmNotificationService.java
  src/main/java/org/baggle/domain/feed/service/FeedService.java
  src/main/java/org/baggle/global/config/MessageConfig.java
  src/main/java/org/baggle/infra/redis/ExpirationListener.java
  src/main/resources/messages_ko_KR.properties
Labels: feat, fix, refactor, 관곤 🍃

#90 [feat] 전체 모임 조회 API 구현
  src/main/java/org/baggle/domain/meeting/controller/MeetingApiController.java
  src/main/java/org/baggle/domain/meeting/domain/Period.java
  src/main/java/org/baggle/domain/meeting/dto/response/GetMeetingResponseDto.java
  src/main/java/org/baggle/domain/meeting/dto/response/MeetingResponseDto.java
  src/main/java/org/baggle/domain/meeting/dto/response/ParticipantResponseDto.java
  src/main/java/org/baggle/domain/meeting/repository/MeetingCountQueryDto.java
  src/main/java/org/baggle/domain/meeting/repository/MeetingRepository.java
  src/main/java/org/baggle/domain/meeting/repository/ParticipationRepository.java
  src/main/java/org/baggle/domain/meeting/service/MeetingService.java
  src/main/java/org/baggle/global/config/MessageConfig.java
  src/main/java/org/baggle/global/error/exception/ErrorCode.java
Labels: feat, fix, chore, 선웅 🍃

#92 [fix] 전체 모임 조회 API 스펙 변경
  src/main/java/org/baggle/domain/meeting/dto/response/MeetingResponseDto.java
  src/main/java/org/baggle/domain/meeting/dto/response/ParticipantResponseDto.java
Labels: fix, del, 선웅 🍃

#95 [feat] p6spy 쿼리 로깅 라이브러리 세팅
  build.gradle
  src/main/java/org/baggle/global/config/CustomP6spySqlFormatter.java
  src/main/java/org/baggle/global/config/P6spyConfig.java
Labels: feat, chore

#97 [fix] 모임 참여 응답 코드 수정
  src/main/java/org/baggle/domain/meeting/controller/ParticipationApiController.java
Labels: fix, 관곤 🍃

#98 [fix] ResponseEntity 응답 HttpStatus 수정
  src/main/java/org/baggle/domain/feed/controller/FeedApiController.java
  src/main/java/org/baggle/domain/meeting/controller/MeetingApiController.java
  src/main/java/org/baggle/domain/meeting/controller/ParticipationApiController.java
  src/main/java/org/baggle/domain/user/controller/AuthApiController.java
Labels: fix, 선웅 🍃

#100 [fix] 전체 모임 조회 API 페이징 오류 수정
  src/main/java/org/baggle/domain/meeting/repository/MeetingRepository.java
Labels: fix, 선웅 🍃

#102 [fix] 모임 상세 response dto 수정
  src/main/java/org/baggle/domain/meeting/dto/response/MeetingDetailResponseDto.java
Labels: fix, 관곤 🍃

#104 [fix] 전체 모임 조회 API 오류 수정
  src/main/java/org/baggle/domain/meeting/repository/MeetingRepository.java
Labels: fix, 선웅 🍃

#106 [feat] 방장 위임 후 모임 탈퇴 api 제작
  src/main/java/org/baggle/domain/meeting/controller/ParticipationApiController.java
  src/main/java/org/baggle/domain/meeting/domain/Meeting.java
  src/main/java/org/baggle/domain/meeting/domain/Participation.java
  src/main/java/org/baggle/domain/meeting/service/ParticipationService.java
Labels: feat, 관곤 🍃

#109 [refactor] Base 클래스 & 예외 핸들링 클래스 리팩터링
  src/main/java/org/baggle/global/common/BaseResponse.java
  src/main/java/org/baggle/global/common/ImageType.java
  src/main/java/org/baggle/global/config/auth/SecurityConfig.java
  src/main/java/org/baggle/global/config/jwt/JwtProvider.java
  src/main/java/org/baggle/global/config/jwt/Token.java
  src/main/java/org/baggle/global/error/dto/ErrorBaseResponse.java
  src/main/java/org/baggle/global/error/handler/GlobalExceptionHandler.java
Labels: fix, refactor, 선웅 🍃

#111 [fix] 모임 생성자의 긴급 버튼 권한 수정
  src/main/java/org/baggle/domain/meeting/domain/Participation.java
Labels: fix, 선웅 🍃

#112 [fix] meeting status 추가
  src/main/java/org/baggle/domain/fcm/scheduler/NotificationScheduler.java
  src/main/java/org/baggle/domain/feed/service/FeedService.java
  src/main/java/org/baggle/domain/meeting/domain/Meeting.java
  src/main/java/org/baggle/domain/meeting/domain/MeetingStatus.java
  src/main/java/org/baggle/domain/meeting/repository/MeetingRepository.java
  src/main/java/org/baggle/domain/meeting/scheduler/MeetingScheduler.java
  src/main/java/org/baggle/domain/meeting/service/MeetingDetailService.java
  src/main/java/org/baggle/global/config/SchedulerConfig.java
  src/main/java/org/baggle/infra/redis/ExpirationListener.java
  src/main/resources/db/migration/V4__modify_meeting_status.sql
Labels: feat, fix, refactor, 관곤 🍃

#114 [fix] 전체 모임 조회 API 변경 사항 적용
  src/main/java/org/baggle/domain/meeting/service/MeetingService.java
Labels: fix, 선웅 🍃

#118 [fix] 긴급 소집 알람 요청 수정
  src/main/java/org/baggle/domain/feed/service/FeedService.java
Labels: fix, 관곤 🍃

#121 [fix] 모임 생성 API 예외 해제
  src/main/java/org/baggle/domain/meeting/service/MeetingService.java
Labels: fix, 선웅 🍃

#122 [fix] 모임 참가자 정렬
  src/main/java/org/baggle/domain/fcm/scheduler/NotificationScheduler.java
  src/main/java/org/baggle/domain/fcm/service/FcmNotificationService.java
  src/main/java/org/baggle/domain/feed/service/FeedService.java
  src/main/java/org/baggle/domain/meeting/service/MeetingDetailService.java
  src/main/java/org/baggle/domain/meeting/service/ParticipationService.java
Labels: feat, fix, 관곤 🍃

#124 [fix] 모임 참여 예외 조건
  src/main/java/org/baggle/domain/meeting/service/ParticipationService.java
Labels: fix, 관곤 🍃

#126 [fix] 모임 참여 예외 우선순위 변경
  src/main/java/org/baggle/domain/meeting/service/ParticipationService.java
Labels: fix, 관곤 🍃

#128 [feat] Jwt 재발급 API 구현
  src/main/java/org/baggle/domain/user/service/AuthService.java
  src/main/java/org/baggle/global/config/jwt/JwtProvider.java
  src/main/java/org/baggle/global/error/exception/ErrorCode.java
Labels: feat, 선웅 🍃

#130 [feat] 로그아웃 API 구현
  src/main/java/org/baggle/domain/user/controller/AuthApiController.java
  src/main/java/org/baggle/domain/user/domain/User.java
  src/main/java/org/baggle/domain/user/service/AuthService.java
Labels: feat, fix, 선웅 🍃

#132 [feat] 예정된 모임 삭제 api 구현
  src/main/java/org/baggle/domain/fcm/service/FcmNotificationProvider.java
  src/main/java/org/baggle/domain/meeting/controller/MeetingApiController.java
  src/main/java/org/baggle/domain/meeting/service/MeetingDetailService.java
  src/main/resources/messages_ko_KR.properties
Labels: feat, fix, 관곤 🍃

#136 [fix] 모임 정보 수정 api 응답 값 수정
  src/main/java/org/baggle/domain/meeting/domain/Meeting.java
  src/main/java/org/baggle/domain/meeting/dto/request/UpdateMeetingInfoRequestDto.java
  src/main/java/org/baggle/domain/meeting/dto/response/UpdateMeetingInfoResponseDto.java
  src/main/java/org/baggle/domain/meeting/service/MeetingDetailService.java
Labels: fix, 관곤 🍃
